trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ContinuousDownload
  jobs:
  - job: Checkout
    steps:
    - checkout: self
    - script: |
        git clone https://github.com/karpanitava/forjenkins.git
      displayName: 'Clone Repository'

- stage: ContinuousBuild
  jobs:
  - job: Build
    steps:
    - script: mvn clean install
      displayName: 'Build Application'




