version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/mywebapp