version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Use a single command entry for the multi-line script
      - |
        echo "Checking for Maven..."
        if ! command -v mvn &> /dev/null; then
          echo "Maven not found, installing..."
          MAVEN_VERSION="3.9.6" # You can choose your preferred Maven version
          wget https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          mv apache-maven-$MAVEN_VERSION /opt/maven
          export PATH="/opt/maven/bin:$PATH"
          echo "Maven installed successfully."
        else
          echo "Maven already installed."
        fi
      - mvn -version # Verify Maven installation (this is a separate command)
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/mywebapp'
